ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: "monthly"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v6.0.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  exclude: '^attic/auto_prod/monitoring\.py$|^attic/auto_prod/main_sync_code\.py$'

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: "v2.8.0"
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/PyCQA/isort
  rev: "6.0.1"
  hooks:
  - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.20.0"
  hooks:
  - id: pyupgrade
    args: ["--py38-plus"]

- repo: https://github.com/psf/black
  rev: "25.1.0"
  hooks:
  - id: black-jupyter

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.17.1"
  hooks:
    - id: mypy
      files: src
      stages: [manual]

- repo: https://github.com/PyCQA/flake8
  rev: "7.3.0"
  hooks:
  - id: flake8
    additional_dependencies: [
      flake8-bugbear,
      flake8-print,
      flake8-docstrings,
      pep8-naming
    ]
    args: ["--docstring-convention", "numpy","--extend-ignore", "E203,E501,D10,N806"]

- repo: https://github.com/kynan/nbstripout
  rev: "0.8.1"
  hooks:
    - id: nbstripout
      args: ["--drop-empty-cells",
             "--extra-keys", "metadata.kernelspec metadata.language_info"]

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.50"
  hooks:
  - id: check-manifest
    stages: [manual]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.4.1"
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.11.0.1"
  hooks:
  - id: shellcheck

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
  - id: python-no-log-warn
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v4.0.0-alpha.8"
  hooks:
    - id: prettier
      types_or: [json]
