codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 10%
    patch: false

github_checks:
    annotations: false

ignore:
  - tests
  - docs

comment: false
